name = "test-git"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "cloudflare-template-prod"

[env.staging]
name = "cloudflare-template-staging"

# Uncomment and configure if you need environment variables
# [vars]
# ORGANIZATION_ID = "your-org-id-here"

# Uncomment if you need to configure secrets
# [secrets]
# EXTERNAL_API_URL = "your-api-url-here" 